name: Build && Unit testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  MONGO_DBUSER: ${{ secrets.MONGO_DBUSER }}
  MONGO_DBPASS: ${{ secrets.MONGO_DBPASS }}
  MONGO_DBHOST: ${{ secrets.MONGO_DBHOST }}
  MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Print environment
      run: |
        echo $MONGO_DBUSER
        echo $MONGO_DBPASS
        echo $MONGO_DBHOST
        echo $MONGO_DBNAME
    - name: MongoDB Server
      uses: timgchile/mongodb-github-action@1.7.4
      with:
       mongodb-version: latest
       mongodb-root-username: ${{ secrets.MONGO_DBUSER }}
       mongodb-root-password: ${{ secrets.MONGO_DBPASS }}

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Populate config file
      run: |
        cp config.js.example config.js
        cat config.js
    
    - name: Install and run tests
      run: |
         npm install
         npm run test
    #- run: npm run build --if-present
    #- run: npm test
